version: 2.1

jobs:
  build:
    docker:
      - image: node
    steps:
      - checkout
      - run: 
          name: build project
          command: | 
            npm install
            npm run export
            cp -r .circleci/ __sapper__/export/.circleci/
      - persist_to_workspace:
          root: __sapper__
          paths: export/* 
  deploy:
    docker:
      - image: node
    steps:
      - checkout
      - attach_workspace:
          at: __sapper__
      - add_ssh_keys:
          fingerprints:
            - "db:fe:7f:33:cc:ff:6d:09:9e:79:77:a3:65:ca:a2:cf"
      - run:
          name: install gh-pages npm package
          command: |
            npm install -g --silent gh-pages
            git config user.email "ci-build@roneal20"
            git config user.name "ci-build"
      - run: 
          Name: Deploy static site to gh-pages branch
          command: gh-pages -t --dist __sapper__/export/

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              only: feature
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: feature