version: 2.1

jobs:
  build:
    docker:
      - image: node
    steps:
      - checkout
      - run: 
          name: build project
          command: | 
            npm install
            npm run export
            cp -r .circleci/ __sapper__/export/.circleci/
      - persist_to_workspace:
          root: __sapper__
          paths: export/* 
  deploy:
    docker:
      - image: node
    steps:
      - checkout
      - attach_workspace:
          at: __sapper__
      - add_ssh_keys:
          fingerprints:
            - "f9:7f:25:9e:dd:ca:77:12:71:12:e9:23:2b:e1:aa:c9"
      - run:
          name: install gh-pages npm package
          command: |
            npm install -g --silent gh-pages
            git config user.email "ci-build@oneal26"
            git config user.name "ci-build@"
      - run: 
          Name: Deploy static site to gh-pages branch
          command: gh-pages -t --dist __sapper__/export/

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              only: feature
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: feature